language: python
matrix:
  include:
    - python: '3.7'
    - python: '3.8'

before_install:
  - python --version

install:
  - pip install pipenv
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - pytest

after_failure:
  - coveralls

notifications:
  email:
    on_success: never
    on_failure: always
